# Generated by Django 2.1.2 on 2018-10-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='images/blog')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
